=== Yang-33/decaton/jsonschema/dist/decaton-processor-properties-schema-draft_6-allow-additional-properties.json
{
  "$schema" : "http://json-schema.org/draft-06/schema#",
  "title" : "Decaton ProcessorProperties",
  "type" : "object",
  "additionalProperties" : true,
  "required" : [ ],
  "properties" : {
    "$schema" : {
      "type" : "string"
    },
    "decaton.ignore.keys" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      },
      "default" : [ ],
      "$comment" : "Property definition: decaton.ignore.keys, type: java.util.List"
    },
    "decaton.processing.rate.per.partition" : {
      "type" : "integer",
      "default" : -1,
      "$comment" : "Property definition: decaton.processing.rate.per.partition, type: java.lang.Long"
    },
    "decaton.partition.concurrency" : {
      "type" : "integer",
      "default" : 1,
      "$comment" : "Property definition: decaton.partition.concurrency, type: java.lang.Integer"
    },
    "decaton.max.pending.records" : {
      "type" : "integer",
      "default" : 10000,
      "$comment" : "Property definition: decaton.max.pending.records, type: java.lang.Integer"
    },
    "decaton.commit.interval.ms" : {
      "type" : "integer",
      "default" : 1000,
      "$comment" : "Property definition: decaton.commit.interval.ms, type: java.lang.Long"
    },
    "decaton.group.rebalance.timeout.ms" : {
      "type" : "integer",
      "default" : 1000,
      "$comment" : "Property definition: decaton.group.rebalance.timeout.ms, type: java.lang.Long"
    },
    "decaton.processing.shutdown.timeout.ms" : {
      "type" : "integer",
      "default" : 0,
      "$comment" : "Property definition: decaton.processing.shutdown.timeout.ms, type: java.lang.Long"
    },
    "decaton.logging.mdc.enabled" : {
      "type" : "boolean",
      "default" : true,
      "$comment" : "Property definition: decaton.logging.mdc.enabled, type: java.lang.Boolean"
    },
    "decaton.client.metrics.micrometer.bound" : {
      "type" : "boolean",
      "default" : false,
      "$comment" : "Property definition: decaton.client.metrics.micrometer.bound, type: java.lang.Boolean"
    },
    "decaton.deferred.complete.timeout.ms" : {
      "type" : "integer",
      "default" : -1,
      "$comment" : "Property definition: decaton.deferred.complete.timeout.ms, type: java.lang.Long"
    },
    "decaton.processor.threads.termination.timeout.ms" : {
      "type" : "integer",
      "default" : 9223372036854775807,
      "$comment" : "Property definition: decaton.processor.threads.termination.timeout.ms, type: java.lang.Long"
    },
    "decaton.per.key.quota.processing.rate" : {
      "type" : "integer",
      "default" : -1,
      "$comment" : "Property definition: decaton.per.key.quota.processing.rate, type: java.lang.Long"
    },
    "decaton.retry.task.in.legacy.format" : {
      "type" : "boolean",
      "default" : false,
      "$comment" : "Property definition: decaton.retry.task.in.legacy.format, type: java.lang.Boolean"
    },
    "decaton.legacy.parse.fallback.enabled" : {
      "type" : "boolean",
      "default" : false,
      "$comment" : "Property definition: decaton.legacy.parse.fallback.enabled, type: java.lang.Boolean"
    }
  }
}

=== Yang-33/decaton/jsonschema/dist/central-dogma-decaton-properties-example.json
{
  "$schema": "https://raw.githubusercontent.com/line/decaton/v9.1.2/jsonschema/dist/decaton-processor-properties-schema-draft_7.json",
  "decaton.partition.concurrency": 1,
  "decaton.processing.rate.per.partition": -1,
  "decaton.max.pending.records": 1000,
  "decaton.ignore.keys": [ ],
  "decaton.group.rebalance.timeout.ms": 30000,
  "decaton.processing.shutdown.timeout.ms": 30000,
  "decaton.deferred.complete.timeout.ms": 600000,
  "decaton.retry.task.in.legacy.format": true,
  "decaton.legacy.parse.fallback.enabled": true,
  "decaton.client.metrics.micrometer.bound": false,
  "decaton.commit.interval.ms": 1000,
  "decaton.logging.mdc.enabled": true,
  "decaton.per.key.quota.processing.rate": -1,
  "decaton.processor.threads.termination.timeout.ms": 9223372036854775807
}
